/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2018-12-20 08:00:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.contact;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer/footer.jsp", Long.valueOf(1545018989238L));
    _jspx_dependants.put("/menu/menu.jsp", Long.valueOf(1545292818330L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Contact for us</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/animate.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/owl.carousel.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/fonts/ionicons/css/ionicons.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/fonts/fontawesome/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Theme Style -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header role=\"banner\">\r\n");
      out.write("      <nav class=\"navbar navbar-expand-md navbar-dark bg-dark\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <a class=\"navbar-brand\" href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">Heal<span>thy</span>\r\n");
      out.write("         \r\n");
      out.write("          </a>\r\n");
      out.write("          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarsExample05\" aria-controls=\"navbarsExample05\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"collapse navbar-collapse\" id=\"navbarsExample05\">\r\n");
      out.write("            <ul class=\"navbar-nav mr-auto pl-lg-5 pl-0\">\r\n");
      out.write("              <li style=\" margin-left: 10px;\" class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link active\" href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">Home</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\" style=\" margin-left:5px; \">\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/about/about.jsp\">About</a>\r\n");
      out.write("              </li>\r\n");
      out.write("             <!--  <li class=\"nav-item dropdown\">\r\n");
      out.write("                <a class=\"nav-link dropdown-toggle\" href=\"services.html\" id=\"dropdown04\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Services</a>\r\n");
      out.write("                <div class=\"dropdown-menu\" aria-labelledby=\"dropdown04\">\r\n");
      out.write("                  <a class=\"dropdown-item\" href=\"services.html\">Body Builder</a>\r\n");
      out.write("                  <a class=\"dropdown-item\" href=\"services.html\">Yoga Pilate</a>\r\n");
      out.write("                  <a class=\"dropdown-item\" href=\"services.html\">Healthy Life</a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </li> -->\r\n");
      out.write("              <li class=\"nav-item\" style=\" margin-left: 5px;\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/news/news.jsp\">News</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\" style=\" margin-left: 5px; \">\r\n");
      out.write("                <a class=\"nav-link\" href=\"news.html\">Schedule</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\" style=\" margin-left: 5px;\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"news.html\">Product</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\" style=\" margin-left: 5px; \">\r\n");
      out.write("                <a class=\"nav-link\" href=\"news.html\">Notification</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\" style=\" margin-left: 5px;\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/contact/contact.jsp\">Contact</a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("              <li class=\"nav-item cta-btn\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/login/css_Login/sign_Up.jsp\">Become a member</a>\r\n");
      out.write("              </li>\r\n");
      out.write("             <li class=\"nav-item cta-btn\">\r\n");
      out.write("                <a  style=\"background:#29aaaa\" class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/login/login.jsp\">Login</a>\r\n");
      out.write("              </li>\r\n");
      out.write("             \r\n");
      out.write("            </ul>\r\n");
      out.write("            \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write(" \r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/magnific-popup-options.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write(" <section class=\"home-slider-loop-false  inner-page owl-carousel\">\r\n");
      out.write("      <div class=\"slider-item\" style=\"background-image: url('../img/bg2.jpg');\">\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row slider-text align-items-center justify-content-center\">\r\n");
      out.write("            <div class=\"col-md-8 text-center col-sm-12 element-animate\">\r\n");
      out.write("              <h1>Contact</h1>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- END slider -->\r\n");
      out.write("\r\n");
      out.write("    <section class=\"section element-animate\">\r\n");
      out.write("      <div class=\"clearfix mb-5 pb-5\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12 text-center heading-wrap\">\r\n");
      out.write("              <h2>Get In Touch</h2>\r\n");
      out.write("              <span class=\"back-text\">Contact</span>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-6\">\r\n");
      out.write("            <form action=\"#\" method=\"post\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6 form-group\">\r\n");
      out.write("                  <label for=\"name\">Name</label>\r\n");
      out.write("                  <input type=\"text\" id=\"name\" class=\"form-control \">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 form-group\">\r\n");
      out.write("                  <label for=\"phone\">Phone</label>\r\n");
      out.write("                  <input type=\"text\" id=\"phone\" class=\"form-control \">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12 form-group\">\r\n");
      out.write("                  \r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12 form-group\">\r\n");
      out.write("                  <label for=\"email\">Email</label>\r\n");
      out.write("                  <input type=\"email\" id=\"email\" class=\"form-control \">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12 form-group\">\r\n");
      out.write("                  <label for=\"message\">Write Message</label>\r\n");
      out.write("                  <textarea name=\"message\" id=\"message\" class=\"form-control \" cols=\"30\" rows=\"8\"></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6 form-group\">\r\n");
      out.write("                  <input type=\"submit\" value=\"Send Message\" class=\"btn btn-primary\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"col-lg-6 pl-2 pl-lg-5\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-8 mx-auto contact-form-contact-info\">\r\n");
      out.write("              <h4 class=\"mb-5\">Contact Details</h4>\r\n");
      out.write("                <p class=\"d-flex\">\r\n");
      out.write("                  <span class=\"ion-ios-location icon mr-5\"></span>\r\n");
      out.write("                  <span>34 Street Name, City Name Here, United States</span>\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("                <p class=\"d-flex\">\r\n");
      out.write("                  <span class=\"ion-ios-telephone icon mr-5\"></span>\r\n");
      out.write("                  <span>+1 242 4942 290</span>\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("                <p class=\"d-flex\">\r\n");
      out.write("                  <span class=\"ion-android-mail icon mr-5\"></span>\r\n");
      out.write("                  <span>info@yourdomain.com</span>\r\n");
      out.write("                </p>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/animate.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/owl.carousel.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/fonts/ionicons/css/ionicons.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/fonts/fontawesome/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Theme Style -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" <footer class=\"site-footer\" role=\"contentinfo\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row mb-5\">\r\n");
      out.write("          <div class=\"col-md-4 mb-5\">\r\n");
      out.write("            <h3>About Us</h3>\r\n");
      out.write("             <img  class=\"mb-5\" src=\"");
      out.print(request.getContextPath());
      out.write("/img/logo.png\" style=\"margin-top: 20px; position: absolute; width: 40% ; margin-bottom: 50px;\">\r\n");
      out.write("          \r\n");
      out.write("            <p class=\"mb-5\">Someone who is lively and active\r\n");
      out.write("            </p>\r\n");
      out.write("          \r\n");
      out.write("            <br>\r\n");
      out.write("             <br>\r\n");
      out.write("            <ul class=\"list-unstyled footer-link d-flex footer-social\">\r\n");
      out.write("              <li><a href=\"#\" class=\"p-2\"><span class=\"fa fa-twitter\"></span></a></li>\r\n");
      out.write("              <li><a href=\"#\" class=\"p-2\"><span class=\"fa fa-facebook\"></span></a></li>\r\n");
      out.write("              <li><a href=\"#\" class=\"p-2\"><span class=\"fa fa-linkedin\"></span></a></li>\r\n");
      out.write("              <li><a href=\"#\" class=\"p-2\"><span class=\"fa fa-instagram\"></span></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-5 mb-5\">\r\n");
      out.write("            <h3>Contact Info</h3>\r\n");
      out.write("            <ul class=\"list-unstyled footer-link\">\r\n");
      out.write("              <li class=\"d-block\">\r\n");
      out.write("                <span class=\"d-block\">Address:</span>\r\n");
      out.write("                <span class=\"text-white\">Khu pho 6, Linh Trung, Thu Duc, Tp HCM</span></li>\r\n");
      out.write("              <li class=\"d-block\"><span class=\"d-block\">Telephone:</span><span class=\"text-white\">0395362466</span></li>\r\n");
      out.write("              <li class=\"d-block\"><span class=\"d-block\">Email:</span><span class=\"text-white\">ngothimylinh@gmail.com</span></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-3 mb-5\">\r\n");
      out.write("            <h3>Quick Links</h3>\r\n");
      out.write("            <ul class=\"list-unstyled footer-link\">\r\n");
      out.write("              <li><a href=\"#\">About</a></li>\r\n");
      out.write("              <li><a href=\"#\">Terms of Use</a></li>\r\n");
      out.write("              <li><a href=\"#\">Disclaimers</a></li>\r\n");
      out.write("              <li><a href=\"#\">Contact</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-3\">\r\n");
      out.write("          \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-12 text-md-center text-left\">\r\n");
      out.write("            <p>&copy; <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --> <br> Demo Images Unsplash</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- END footer -->\r\n");
      out.write("\r\n");
      out.write("    <!-- loader -->\r\n");
      out.write("    <div id=\"loader\" class=\"show fullscreen\"><svg class=\"circular\" width=\"48px\" height=\"48px\"><circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke=\"#eeeeee\"/><circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#f4b214\"/></svg></div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/magnific-popup-options.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
