/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2018-12-20 06:39:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>PTTK-HTTT-GYMandFIT</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/animate.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/owl.carousel.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/fonts/ionicons/css/ionicons.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/fonts/fontawesome/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Theme Style -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\">\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("  \r\n");
      out.write("   \r\n");
      out.write("     \r\n");
      out.write("    <section class=\"home-slider owl-carousel\">\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"slider-item\" style=\"background-image: url('");
      out.print(request.getContextPath());
      out.write("/img/slider-1.jpg');\">\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row slider-text align-items-center justify-content-center\">\r\n");
      out.write("            <div class=\"col-md-8 text-center col-sm-12 element-animate\">\r\n");
      out.write("              <h1>Health is wealth</h1>\r\n");
      out.write("              <p class=\"mb-5\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi unde impedit, necessitatibus, soluta sit quam minima expedita atque corrupti reiciendis.</p>\r\n");
      out.write("               <p><a href=\"#\" class=\"btn btn-white btn-outline-white\">Comming here </a> <a href=\"#\" class=\"btn btn-link btn-white\">Let go</a></p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"slider-item\" style=\"background-image: url('");
      out.print(request.getContextPath());
      out.write("/img/slider-2.jpg');\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row slider-text align-items-center justify-content-center\">\r\n");
      out.write("            <div class=\"col-md-8 text-center col-sm-12 element-animate\">\r\n");
      out.write("              <h1>Join Fitnezz Today</h1>\r\n");
      out.write("              <p class=\"mb-5\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi unde impedit, necessitatibus, soluta sit quam minima expedita atque corrupti reiciendis.</p>\r\n");
      out.write("              <p><a href=\"#\" class=\"btn btn-white btn-outline-white\">Comming here </a> <a href=\"#\" class=\"btn btn-link btn-white\">Let go</a></p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- END slider -->\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <section class=\"section element-animate\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"clearfix mb-5 pb-5\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12 text-center heading-wrap\">\r\n");
      out.write("              <h2>Featured Classes</h2>\r\n");
      out.write("              <span class=\"back-text\">The Classes</span>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"owl-carousel centernonloop\">\r\n");
      out.write("        <a href=\"#\" class=\"item-class\">\r\n");
      out.write("          <div class=\"text\">\r\n");
      out.write("            <p class=\"class-price\">450.000VND</p>\r\n");
      out.write("            <h2 class=\"class-heading\">Fitness Class Name Here</h2>\r\n");
      out.write("          </div>\r\n");
      out.write("          <img src=\"");
      out.print(request.getContextPath());
      out.write("/img/gym4.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#\" class=\"item-class\">\r\n");
      out.write("          <div class=\"text\">\r\n");
      out.write("            <p class=\"class-price\">500.000VND</p>\r\n");
      out.write("            <h2 class=\"class-heading\">Fitness Class Name Here</h2>\r\n");
      out.write("          </div>\r\n");
      out.write("          <img src=\"");
      out.print(request.getContextPath());
      out.write("/img/gym2.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#\" class=\"item-class\">\r\n");
      out.write("          <div class=\"text\">\r\n");
      out.write("            <p class=\"class-price\">500.000VND</p>\r\n");
      out.write("            <h2 class=\"class-heading\">Fitness Class Name Here</h2>\r\n");
      out.write("          </div>\r\n");
      out.write("          <img src=\"");
      out.print(request.getContextPath());
      out.write("/img/gym3.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#\" class=\"item-class\">\r\n");
      out.write("          <div class=\"text\">\r\n");
      out.write("            <p class=\"class-price\">300.000VND</p>\r\n");
      out.write("            <h2 class=\"class-heading\">Fitness Class Name Here</h2>\r\n");
      out.write("          </div>\r\n");
      out.write("          <img src=\"");
      out.print(request.getContextPath());
      out.write("/img/gym5.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section> <!-- .section -->\r\n");
      out.write("\r\n");
      out.write("    <section class=\"section bg-light element-animate\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"clearfix mb-5 pb-5\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12 text-center heading-wrap\">\r\n");
      out.write("              <h2>Our Schedule</h2>\r\n");
      out.write("              <span class=\"back-text-dark\">Schedule</span>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"row no-gutters\">\r\n");
      out.write("          <div class=\"col-md-6\">\r\n");
      out.write("            <div class=\"sched d-block d-lg-flex\">\r\n");
      out.write("              <div class=\"bg-image order-2\" style=\"background-image: url('");
      out.print(request.getContextPath());
      out.write("/img/gym4.jpg');\"></div>\r\n");
      out.write("              <div class=\"text order-1\">\r\n");
      out.write("                <h3>Fitness Class Name Here</h3>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto illo delectus...</p>\r\n");
      out.write("                <p class=\"sched-time\">\r\n");
      out.write("                  <span><span class=\"fa fa-clock-o\"></span> 5:30 PM</span> <br>\r\n");
      out.write("                  <span><span class=\"fa fa-calendar\"></span> April 22, 2018</span> <br>\r\n");
      out.write("                </p>\r\n");
      out.write("                <p><a href=\"#\" class=\"btn btn-primary btn-sm\">Join from 150.000vnd</a></p>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"sched d-block d-lg-flex\">\r\n");
      out.write("              <div class=\"bg-image\" style=\"background-image: url('");
      out.print(request.getContextPath());
      out.write("/img/gym2.jpg');\"></div>\r\n");
      out.write("              <div class=\"text\">\r\n");
      out.write("                <h3>Fitness Class Name Here</h3>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto illo delectus...</p>\r\n");
      out.write("                <p class=\"sched-time\">\r\n");
      out.write("                  <span><span class=\"fa fa-clock-o\"></span> 5:30 PM</span> <br>\r\n");
      out.write("                  <span><span class=\"fa fa-calendar\"></span> April 22, 2018</span> <br>\r\n");
      out.write("                </p>\r\n");
      out.write("                <p><a href=\"#\" class=\"btn btn-primary btn-sm\">Join from 150.000vnd</a></p>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-6\">\r\n");
      out.write("            <div class=\"sched d-block d-lg-flex\">\r\n");
      out.write("              <div class=\"bg-image order-2\" style=\"background-image: url('");
      out.print(request.getContextPath());
      out.write("/img/gym3.jpg');\"></div>\r\n");
      out.write("              <div class=\"text order-1\">\r\n");
      out.write("                <h3>Fitness Class Name Here</h3>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto illo delectus...</p>\r\n");
      out.write("                <p class=\"sched-time\">\r\n");
      out.write("                  <span><span class=\"fa fa-clock-o\"></span> 5:30 PM</span> <br>\r\n");
      out.write("                  <span><span class=\"fa fa-calendar\"></span> April 22, 2018</span> <br>\r\n");
      out.write("                </p>\r\n");
      out.write("                <p><a href=\"#\" class=\"btn btn-primary btn-sm\">Join from 150.000vnd</a></p>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"sched d-block d-lg-flex\">\r\n");
      out.write("              <div class=\"bg-image\" style=\"background-image: url('");
      out.print(request.getContextPath());
      out.write("/img/gym5.jpg');\"></div>\r\n");
      out.write("              <div class=\"text\">\r\n");
      out.write("                <h3>Fitness Class Name Here</h3>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto illo delectus...</p>\r\n");
      out.write("                <p class=\"sched-time\">\r\n");
      out.write("                  <span><span class=\"fa fa-clock-o\"></span> 5:30 PM</span> <br>\r\n");
      out.write("                  <span><span class=\"fa fa-calendar\"></span> April 22, 2018</span> <br>\r\n");
      out.write("                </p>\r\n");
      out.write("                <p><a href=\"#\" class=\"btn btn-primary btn-sm\">Join from 150.000vnd</a></p>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </section> <!-- .section -->\r\n");
      out.write("\r\n");
      out.write("    <section class=\"section element-animate\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"clearfix mb-5 pb-5\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12 text-center heading-wrap\">\r\n");
      out.write("              <h2>Expert Trainers</h2>\r\n");
      out.write("              <span class=\"back-text\">Our Trainers</span>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"major-caousel js-carousel-1 owl-carousel\">\r\n");
      out.write("              <div>\r\n");
      out.write("                <div class=\"media d-block media-custom text-center\">\r\n");
      out.write("                  <a href=\"\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/img/lsi1.jpg\" alt=\"Image Placeholder\" class=\"img-fluid\"></a>\r\n");
      out.write("                  <div class=\"media-body\">\r\n");
      out.write("                    <h3 class=\"mt-0 text-black\">Phạm Văn Mách</h3>\r\n");
      out.write("                    <p class=\"lead\">Gym Trainer</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div>\r\n");
      out.write("              <div class=\"media d-block media-custom text-center\">\r\n");
      out.write("                  <a href=\"#\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/img/lsi2.jpg\" alt=\"Image Placeholder\" class=\"img-fluid\"></a>\r\n");
      out.write("                  <div class=\"media-body\">\r\n");
      out.write("                    <h3 class=\"mt-0 text-black\">Nguyễn Thị Mỹ Linh</h3>\r\n");
      out.write("                    <p class=\"lead\">Gym Trainer</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div>\r\n");
      out.write("                <div class=\"media d-block media-custom text-center\">\r\n");
      out.write("                  <a href=\"#\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/img/lsi3.jpg\" alt=\"Image Placeholder\" class=\"img-fluid\"></a>\r\n");
      out.write("                  <div class=\"media-body\">\r\n");
      out.write("                    <h3 class=\"mt-0 text-black\">Lý Đức</h3>\r\n");
      out.write("                    <p class=\"lead\">Gym Trainer</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("               <div>\r\n");
      out.write("              <div class=\"media d-block media-custom text-center\">\r\n");
      out.write("                <a href=\"#\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/img/gym6.jpg\" alt=\"Image Placeholder\" class=\"img-fluid\"></a>\r\n");
      out.write("                <div class=\"media-body\">\r\n");
      out.write("                  <h3 class=\"mt-0 text-black\">Mellisa Howard</h3>\r\n");
      out.write("                  <p class=\"lead\">Gym Trainer</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("             <div class=\"media d-block media-custom text-center\">\r\n");
      out.write("                  <a href=\"adoption-single.html\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/img/lsi3.jpg\" alt=\"Image Placeholder\" class=\"img-fluid\"></a>\r\n");
      out.write("                  <div class=\"media-body\">\r\n");
      out.write("                    <h3 class=\"mt-0 text-black\">Lý Đức</h3>\r\n");
      out.write("                      <p class=\"lead\">Gym Trainer</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("             <div class=\"media d-block media-custom text-center\">\r\n");
      out.write("                <a href=\"adoption-single.html\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/img/lsi1.jpg\" alt=\"Image Placeholder\" class=\"img-fluid\"></a>\r\n");
      out.write("                <div class=\"media-body\">\r\n");
      out.write("                  <h3 class=\"mt-0 text-black\">Phạm Văn Mách</h3>\r\n");
      out.write("                   <p class=\"lead\">Gym Trainer</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("              \r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- END slider -->\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      \r\n");
      out.write("    </section> <!-- .section -->\r\n");
      out.write("\r\n");
      out.write("    <section class=\"section element-animate\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"clearfix mb-5 pb-5\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12 text-center heading-wrap\">\r\n");
      out.write("              <h2>Testimonial</h2>\r\n");
      out.write("              <span class=\"back-text\">Testimonial</span>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-4\">\r\n");
      out.write("            <blockquote class=\"testimonial\">\r\n");
      out.write("              <p>&ldquo; Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolor, obcaecati? Quis eum minus, sequi atque quisquam ducimus aliquam veritatis nobis cum iusto neque enim explicabo maxime natus doloribus, fuga sunt. &rdquo;</p>\r\n");
      out.write("              <div class=\"d-flex author\">\r\n");
      out.write("                <img src=\"");
      out.print(request.getContextPath());
      out.write("/img/lsi2.jpg\" alt=\"\" class=\"mr-4\">\r\n");
      out.write("                <div class=\"author-info\">\r\n");
      out.write("                  <h4>Nguyễn Thị Mỹ Linh</h4>\r\n");
      out.write("                  <p>CEO, VimGroup Company</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>  \r\n");
      out.write("            </blockquote>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4\">\r\n");
      out.write("            <blockquote class=\"testimonial\">\r\n");
      out.write("              <p>&ldquo; Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolor, obcaecati? Quis eum minus, sequi atque quisquam ducimus aliquam veritatis nobis cum iusto neque enim explicabo maxime natus doloribus, fuga sunt. &rdquo;</p>\r\n");
      out.write("              <div class=\"d-flex author\">\r\n");
      out.write("                <img src=\"");
      out.print(request.getContextPath());
      out.write("/img/lsi3.jpg\" alt=\"\" class=\"mr-4\">\r\n");
      out.write("                <div class=\"author-info\">\r\n");
      out.write("                  <h4>Lý Đức</h4>\r\n");
      out.write("                  <p>CEO, Gym Company</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>  \r\n");
      out.write("            </blockquote>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4\">\r\n");
      out.write("            <blockquote class=\"testimonial\">\r\n");
      out.write("              <p>&ldquo; Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolor, obcaecati? Quis eum minus, sequi atque quisquam ducimus aliquam veritatis nobis cum iusto neque enim explicabo maxime natus doloribus, fuga sunt. &rdquo;</p>\r\n");
      out.write("              <div class=\"d-flex author\">\r\n");
      out.write("                <img src=\"");
      out.print(request.getContextPath());
      out.write("/img/lsi1.jpg\" alt=\"\" class=\"mr-4\">\r\n");
      out.write("                <div class=\"author-info\">\r\n");
      out.write("                  <h4>Phạm Văn Mách</h4>\r\n");
      out.write("                  <p>CEO, XYZ Company</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>  \r\n");
      out.write("            </blockquote>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section> <!-- .section -->\r\n");
      out.write("\r\n");
      out.write("    <section class=\"section element-animate\">\r\n");
      out.write("      <div class=\"clearfix mb-5 pb-5\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12 text-center heading-wrap\">\r\n");
      out.write("              <h2>Blog</h2>\r\n");
      out.write("              <span class=\"back-text\">Our Blog</span>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-6\">\r\n");
      out.write("            <div class=\"blog d-block d-lg-flex\">\r\n");
      out.write("              <div class=\"bg-image\" style=\"background-image: url('");
      out.print(request.getContextPath());
      out.write("/img/gym3.jpg');\"></div>\r\n");
      out.write("              <div class=\"text\">\r\n");
      out.write("                <h3>Fitness Class Name Here</h3>\r\n");
      out.write("                <p class=\"sched-time\">\r\n");
      out.write("                  <span><span class=\"fa fa-calendar\"></span> April 22, 2018</span> <br>\r\n");
      out.write("                </p>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto illo delectus...</p>\r\n");
      out.write("                \r\n");
      out.write("                <p><a href=\"#\" class=\"btn btn-primary btn-sm\">Read More</a></p>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-6\">\r\n");
      out.write("            <div class=\"blog d-block d-lg-flex\">\r\n");
      out.write("              <div class=\"bg-image\" style=\"background-image: url('");
      out.print(request.getContextPath());
      out.write("/img/gym5.jpg');\"></div>\r\n");
      out.write("              <div class=\"text\">\r\n");
      out.write("                <h3>Fitness Class Name Here</h3>\r\n");
      out.write("                <p class=\"sched-time\">\r\n");
      out.write("                  <span><span class=\"fa fa-calendar\"></span> April 22, 2018</span> <br>\r\n");
      out.write("                </p>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto illo delectus...</p>\r\n");
      out.write("                \r\n");
      out.write("                <p><a href=\"#\" class=\"btn btn-primary btn-sm\">Read More</a></p>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </section> <!-- .section -->\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
