/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2018-12-20 11:45:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.Product;
import dao.Product_DAO;
import java.util.ArrayList;

public final class buyProduct1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/menu/menu.jsp", Long.valueOf(1545300884806L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.Product");
    _jspx_imports_classes.add("dao.Product_DAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Buy Product</title>\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href=\"css/form.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Exo+2'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery1.min.js\"></script>\r\n");
      out.write("<!-- start menu -->\r\n");
      out.write("<link href=\"css/megamenu.css\" rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\tmedia=\"all\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/megamenu.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$(\".megamenu\").megamenu();\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!--start slider -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/fwslider.css\" media=\"all\">\r\n");
      out.write("<script src=\"js/jquery-ui.min.js\"></script>\r\n");
      out.write("<script src=\"js/css3-mediaqueries.js\"></script>\r\n");
      out.write("<script src=\"js/fwslider.js\"></script>\r\n");
      out.write("<!--end slider -->\r\n");
      out.write("<script src=\"js/jquery.easydropdown.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("     ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/animate.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/owl.carousel.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/fonts/ionicons/css/ionicons.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/fonts/fontawesome/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Theme Style -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header role=\"banner\">\r\n");
      out.write("      <nav class=\"navbar navbar-expand-md navbar-dark bg-dark\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <a class=\"navbar-brand\" href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">Heal<span>thy</span>\r\n");
      out.write("         \r\n");
      out.write("          </a>\r\n");
      out.write("          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarsExample05\" aria-controls=\"navbarsExample05\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"collapse navbar-collapse\" id=\"navbarsExample05\">\r\n");
      out.write("            <ul class=\"navbar-nav mr-auto pl-lg-5 pl-0\">\r\n");
      out.write("              <li style=\" margin-left: 10px;\" class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link active\" href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">Home</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\" style=\" margin-left:5px; \">\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/about/about.jsp\">About</a>\r\n");
      out.write("              </li>\r\n");
      out.write("             <!--  <li class=\"nav-item dropdown\">\r\n");
      out.write("                <a class=\"nav-link dropdown-toggle\" href=\"services.html\" id=\"dropdown04\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Services</a>\r\n");
      out.write("                <div class=\"dropdown-menu\" aria-labelledby=\"dropdown04\">\r\n");
      out.write("                  <a class=\"dropdown-item\" href=\"services.html\">Body Builder</a>\r\n");
      out.write("                  <a class=\"dropdown-item\" href=\"services.html\">Yoga Pilate</a>\r\n");
      out.write("                  <a class=\"dropdown-item\" href=\"services.html\">Healthy Life</a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </li> -->\r\n");
      out.write("              <li class=\"nav-item\" style=\" margin-left: 5px;\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/news/news.jsp\">News</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\" style=\" margin-left: 5px; \">\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/schedule/schedule.jsp\">Schedule</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\" style=\" margin-left: 5px;\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"news.html\">Product</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\" style=\" margin-left: 5px; \">\r\n");
      out.write("                <a class=\"nav-link\" href=\"news.html\">Notification</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\" style=\" margin-left: 5px;\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/contact/contact.jsp\">Contact</a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("              <li class=\"nav-item cta-btn\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/login/css_Login/sign_Up.jsp\">Become a member</a>\r\n");
      out.write("              </li>\r\n");
      out.write("             <li class=\"nav-item cta-btn\">\r\n");
      out.write("                <a  style=\"background:#29aaaa\" class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/login/login.jsp\">Login</a>\r\n");
      out.write("              </li>\r\n");
      out.write("             \r\n");
      out.write("            </ul>\r\n");
      out.write("            \r\n");
      out.write("          </div>\r\n");
      out.write("      \r\n");
      out.write("       \r\n");
      out.write("        </div>\r\n");
      out.write("         \r\n");
      out.write("      </nav>\r\n");
      out.write("  \r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/magnific-popup-options.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- start slider -->\r\n");
      out.write("\t<div id=\"fwslider\">\r\n");
      out.write("\t\t<div class=\"slider_container\">\r\n");
      out.write("\t\t\t<div class=\"slide\">\r\n");
      out.write("\t\t\t\t<!-- Slide image -->\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/img/bg.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t<!-- /Slide image -->\r\n");
      out.write("\t\t\t\t<!-- Texts container -->\r\n");
      out.write("\t\t\t\t<div class=\"slide_content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"slide_content_wrap\">\r\n");
      out.write("\t\t\t\t\t\t<!-- Text title -->\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"title\">Gym and Fitness</h4>\r\n");
      out.write("\t\t\t\t\t\t<!-- /Text title -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Text description -->\r\n");
      out.write("\t\t\t\t\t\t<p class=\"description\"></p>\r\n");
      out.write("\t\t\t\t\t\t<!-- /Text description -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /Texts container -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /Duplicate to create more slides -->\r\n");
      out.write("\t\t\t<div class=\"slide\">\r\n");
      out.write("\t\t\t\t<img src=\"images/b2.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t<div class=\"slide_content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"slide_content_wrap\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"title\">Gym and Fitness</h4>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"description\">Heathy for you</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--/slide -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"timers\"></div>\r\n");
      out.write("\t\t<div class=\"slidePrev\">\r\n");
      out.write("\t\t\t<span></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"slideNext\">\r\n");
      out.write("\t\t\t<span></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--/slider -->\r\n");
      out.write("\t<h2 class=\"head\">Sản phẩm nổi bật</h2>\r\n");
      out.write("\t");

		ArrayList<Product> listProduct = new Product_DAO().getList();
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"main\">\r\n");
      out.write("\t\t");

			for (int i = 0; i < listProduct.size(); i++) {
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"section group\">\r\n");
      out.write("\t\t\t<div class=\"cont span_2_of_3\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"top-box\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col_1_of_3 span_1_of_3\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"inner_content clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"Buy_Product?maSp=");
      out.print(listProduct.get(i).getId());
      out.write("\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product_image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write('/');
      out.print(listProduct.get(i).getUrl());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"sale-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"on_sale title_shop\">New</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"price\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"cart-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"title\">");
      out.print(listProduct.get(i).getName());
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"price1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"actual\">");
      out.print(listProduct.get(i).getPrice());
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"cart-right\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t");

		}
	
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
