CREATE TABLE PRODUCE(
	PRODUCE_ID INT IDENTITY PRIMARY KEY,
	PRODUCE_CODE VARCHAR(10) NOT NULL,
	PRODUCE_NAME NVARCHAR(50) NOT NULL,
	PRODUCE_DESCRIPTION NVARCHAR(255),
	IMAGE VARCHAR(50),
	PRICE FLOAT,
	PRODUCE_QUANTITY INT,
	TYPE INT,
	PRODUCE_STATUS INT,
)
GO

CREATE TABLE SCHEDULE(
	SCHEDULE_ID INT IDENTITY PRIMARY KEY,
	SCHEDULE_CODE VARCHAR(10) NOT NULL,
	SCHEDULE_NAME NVARCHAR(255) ,
	SCHEDULE_DESCRIPTION NVARCHAR(255),
	START_DATE DATE,
	END_DATE DATE,
	SCHEDULE_EVALUTE NVARCHAR(255),
	SCHEDULE_STATUS INT,
)
GO

CREATE TABLE NEWS(
	NEWS_ID INT IDENTITY PRIMARY KEY,
	NEWS_CODE VARCHAR(50) NOT NULL,
	NEWS_NAME NVARCHAR(50) ,
	NEWS_DESCRIPTION NVARCHAR(255),
	NEWS_URL_IMG VARCHAR(50),
	NEWS_URL_SAVENEWS VARCHAR(50),
)
GO

CREATE TABLE ROLE(
	ROLE_ID INT IDENTITY PRIMARY KEY,
	ROLE_CODE VARCHAR(10) NOT NULL,
	ROLE_NAME NVARCHAR(50) NOT NULL,
	ROLE_DESCRIPTION NVARCHAR(255),
	ROLE_STATUS INT,
)
GO

CREATE TABLE COURSE(
	COURSE_ID INT IDENTITY PRIMARY KEY,
	COURSE_CODE VARCHAR(10) NOT NULL,
	COURSE_NAME NVARCHAR(50),
	COURSE_DESCRIPTION NVARCHAR(255),
	START_DATE DATE,
	END_DATE DATE,
	COURSE_STATUS INT,
)
GO

CREATE TABLE NOTIFICATIONS (
	NOTIFI_ID INT IDENTITY PRIMARY KEY,
	NOTIFI_CODE VARCHAR(10) NOT NULL,
	NOTIFI_NAME NVARCHAR(50),
	NOTIFI_DESCRIPTION NVARCHAR(255),
)
GO

CREATE TABLE USERS(
	USERS_ID INT IDENTITY PRIMARY KEY,
	USERS_CODE VARCHAR(10) NOT NULL,
	USERS_NAME NVARCHAR(50) NOT NULL,
	USERS_ROLE INT NOT NULL,
	SEX INT,
	DATEOFBIR DATE,
	PHONE VARCHAR(10),
	CITY NVARCHAR(10),
	TOWN NVARCHAR(10),
	ADDRESS NVARCHAR(60),
	EMAIL VARCHAR(50),
	BANK_ACCOUNT VARCHAR(20),
	BANK_NAME NVARCHAR(30),
	USERS_DESCRIPTION NVARCHAR(255),
	SCHEDULE_ID INT,
	USERS_STATUS INT,
	CONSTRAINT FK_USER_ROLE FOREIGN KEY (USERS_ROLE) REFERENCES ROLE(ROLE_ID),
	CONSTRAINT FK_USER_SCHEDULE FOREIGN KEY (SCHEDULE_ID) REFERENCES SCHEDULE(SCHEDULE_ID),
)
GO

CREATE TABLE MAP_COURSE(
MAP_COURSE_ID INT IDENTITY PRIMARY KEY,
USERS_ID INT,
COURSE_ID INT,
CONSTRAINT FK_MAP_USERS FOREIGN KEY (USERS_ID) REFERENCES USESRS(USERS_ID),
CONSTRAINT FK_MAP_COURSE FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
)
GO

CREATE TABLE MAIL(
MAIL_ID INT IDENTITY PRIMARY KEY,
NOTIFI_ID INT,
SEND_ID INT,
APPLY_ID INT,
CONSTRAINT NOTIFI_ID FOREIGN KEY (NOTIFI_ID) REFERENCES NOTIFICATIONS(NOTIFI_ID),
CONSTRAINT SEND_ID FOREIGN KEY (SEND_ID) REFERENCES USERS(USERS_ID),
CONSTRAINT APPLY_ID FOREIGN KEY (APPLY_ID) REFERENCES USERS(USERS_ID)
)
GO

CREATE TABLE DETAIL_SCHEDULE(
	DETAIL_SCHEDULE_ID INT IDENTITY PRIMARY KEY,
	SCHEDULE_ID INT NOT NULL,
	WEEK INT,
	DAY INT,
	MONTH INT,
	YEAR INT,
	DESCIPTION NVARCHAR(255),
	STATUS INT,
	CONSTRAINT FK_SCHEDULE_ID FOREIGN KEY (SCHEDULE_ID) REFERENCES SCHEDULE(SCHEDULE_ID)
)
GO

CREATE TABLE ACCOUNT(
USERS_ID INT FOREIGN KEY (USERS_ID) REFERENCES USERS(USERS_ID),
USERNAME VARCHAR(10) not null,
PASSWORD VARCHAR(50) NOT NULL
)
GO


CREATE TABLE MAP_USERS(
MANAGE_ID INT FOREIGN KEY (MANAGE_ID) REFERENCES USERS(USERS_ID),
USERS_ID INT FOREIGN KEY (USERS_ID) REFERENCES USERS(USERS_ID),
STATUS INT
)

ALTER TABLE USERS
ADD CONSTRAINT USERS_STATUS
DEFAULT 1 FOR USERS_STATUS

ALTER TABLE COURSE
ADD CONSTRAINT COURSE_STATUS
DEFAULT 1 FOR COURSE_STATUS

ALTER TABLE MAP_COURSE
ADD TRAINER_ID INT FOREIGN KEY (USERS_ID) REFERENCES USERS(USERS_ID)

