/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2018-12-20 10:36:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.schedule;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class schedule_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer/footer.jsp", Long.valueOf(1545018989238L));
    _jspx_dependants.put("/menu/menu.jsp", Long.valueOf(1545300884806L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("/* Add a black background color to the top navigation bar */\r\n");
      out.write(".topnav {\r\n");
      out.write("\tmargin-top: 67px;\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\tmargin-left: 800px;\r\n");
      out.write("\tz-index: 10000;\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Style the links inside the navigation bar */\r\n");
      out.write(".topnav a {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding: 14px 16px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tfont-size: 17px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Change the color of links on hover */\r\n");
      out.write(".topnav a:hover {\r\n");
      out.write("\tbackground-color: black;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Style the \"active\" element to highlight the current page */\r\n");
      out.write(".topnav a.active {\r\n");
      out.write("\tbackground-color: #2196F3;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Style the search box inside the navigation bar */\r\n");
      out.write(".topnav input[type=text] {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tpadding: 6px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tmargin-top: 8px;\r\n");
      out.write("\tmargin-right: 16px;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\twidth: 500px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* When the screen is less than 600px wide, stack the links and the search field vertically instead of horizontally */\r\n");
      out.write("@media screen and (max-width: 600px) {\r\n");
      out.write("\t.topnav a, .topnav input[type=text] {\r\n");
      out.write("\t\tfloat: none;\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t\ttext-align: left;\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\tmargin: 0;\r\n");
      out.write("\t\tpadding: 14px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.topnav input[type=text] {\r\n");
      out.write("\t\tborder: 1px solid #ccc;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Schedule</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/animate.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/owl.carousel.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/fonts/ionicons/css/ionicons.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/fonts/fontawesome/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Theme Style -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header role=\"banner\">\r\n");
      out.write("      <nav class=\"navbar navbar-expand-md navbar-dark bg-dark\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <a class=\"navbar-brand\" href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">Heal<span>thy</span>\r\n");
      out.write("         \r\n");
      out.write("          </a>\r\n");
      out.write("          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarsExample05\" aria-controls=\"navbarsExample05\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"collapse navbar-collapse\" id=\"navbarsExample05\">\r\n");
      out.write("            <ul class=\"navbar-nav mr-auto pl-lg-5 pl-0\">\r\n");
      out.write("              <li style=\" margin-left: 10px;\" class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link active\" href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">Home</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\" style=\" margin-left:5px; \">\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/about/about.jsp\">About</a>\r\n");
      out.write("              </li>\r\n");
      out.write("             <!--  <li class=\"nav-item dropdown\">\r\n");
      out.write("                <a class=\"nav-link dropdown-toggle\" href=\"services.html\" id=\"dropdown04\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Services</a>\r\n");
      out.write("                <div class=\"dropdown-menu\" aria-labelledby=\"dropdown04\">\r\n");
      out.write("                  <a class=\"dropdown-item\" href=\"services.html\">Body Builder</a>\r\n");
      out.write("                  <a class=\"dropdown-item\" href=\"services.html\">Yoga Pilate</a>\r\n");
      out.write("                  <a class=\"dropdown-item\" href=\"services.html\">Healthy Life</a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </li> -->\r\n");
      out.write("              <li class=\"nav-item\" style=\" margin-left: 5px;\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/news/news.jsp\">News</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\" style=\" margin-left: 5px; \">\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/schedule/schedule.jsp\">Schedule</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\" style=\" margin-left: 5px;\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"news.html\">Product</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\" style=\" margin-left: 5px; \">\r\n");
      out.write("                <a class=\"nav-link\" href=\"news.html\">Notification</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\" style=\" margin-left: 5px;\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/contact/contact.jsp\">Contact</a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("              <li class=\"nav-item cta-btn\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/login/css_Login/sign_Up.jsp\">Become a member</a>\r\n");
      out.write("              </li>\r\n");
      out.write("             <li class=\"nav-item cta-btn\">\r\n");
      out.write("                <a  style=\"background:#29aaaa\" class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/login/login.jsp\">Login</a>\r\n");
      out.write("              </li>\r\n");
      out.write("             \r\n");
      out.write("            </ul>\r\n");
      out.write("            \r\n");
      out.write("          </div>\r\n");
      out.write("      \r\n");
      out.write("       \r\n");
      out.write("        </div>\r\n");
      out.write("         \r\n");
      out.write("      </nav>\r\n");
      out.write("  \r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/magnific-popup-options.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"topnav\">\r\n");
      out.write("\r\n");
      out.write("\t\t<input type=\"text\" placeholder=\"Search..\"> <img\r\n");
      out.write("\t\t\tstyle=\"width: 10%; margin-left: 430px; margin-top: 15px; position: absolute;\"\r\n");
      out.write("\t\t\talt=\"\" src=\"");
      out.print(request.getContextPath());
      out.write("/img/iconsearch.jpg\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<section style=\"z-index:-2\" class=\"section bg-light element-animate\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"clearfix mb-5 pb-5\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12 text-center heading-wrap\">\r\n");
      out.write("\t\t\t\t\t<h2>Our Schedule</h2>\r\n");
      out.write("\t\t\t\t\t<span class=\"back-text-dark\">Schedule</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row no-gutters\">\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<div class=\"sched d-block d-lg-flex\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-image order-2\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"background-image: url('");
      out.print(request.getContextPath());
      out.write("/img/gym4.jpg');\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"text order-1\">\r\n");
      out.write("\t\t\t\t\t\t<h3>Fitness Class Name Here</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\n");
      out.write("\t\t\t\t\t\t\tArchitecto illo delectus...</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"sched-time\">\r\n");
      out.write("\t\t\t\t\t\t\t<span><span class=\"fa fa-clock-o\"></span> 5:30 PM</span> <br>\r\n");
      out.write("\t\t\t\t\t\t\t<span><span class=\"fa fa-calendar\"></span> April 22, 2018</span>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary btn-sm\">Join from\r\n");
      out.write("\t\t\t\t\t\t\t\t150.000vnd</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"sched d-block d-lg-flex\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-image\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"background-image: url('");
      out.print(request.getContextPath());
      out.write("/img/gym2.jpg');\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t<h3>Fitness Class Name Here</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\n");
      out.write("\t\t\t\t\t\t\tArchitecto illo delectus...</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"sched-time\">\r\n");
      out.write("\t\t\t\t\t\t\t<span><span class=\"fa fa-clock-o\"></span> 5:30 PM</span> <br>\r\n");
      out.write("\t\t\t\t\t\t\t<span><span class=\"fa fa-calendar\"></span> April 22, 2018</span>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary btn-sm\">Join from\r\n");
      out.write("\t\t\t\t\t\t\t\t150.000vnd</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<div class=\"sched d-block d-lg-flex\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-image order-2\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"background-image: url('");
      out.print(request.getContextPath());
      out.write("/img/gym3.jpg');\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"text order-1\">\r\n");
      out.write("\t\t\t\t\t\t<h3>Fitness Class Name Here</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\n");
      out.write("\t\t\t\t\t\t\tArchitecto illo delectus...</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"sched-time\">\r\n");
      out.write("\t\t\t\t\t\t\t<span><span class=\"fa fa-clock-o\"></span> 5:30 PM</span> <br>\r\n");
      out.write("\t\t\t\t\t\t\t<span><span class=\"fa fa-calendar\"></span> April 22, 2018</span>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary btn-sm\">Join from\r\n");
      out.write("\t\t\t\t\t\t\t\t150.000vnd</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"sched d-block d-lg-flex\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-image\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"background-image: url('");
      out.print(request.getContextPath());
      out.write("/img/gym5.jpg');\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t<h3>Fitness Class Name Here</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\n");
      out.write("\t\t\t\t\t\t\tArchitecto illo delectus...</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"sched-time\">\r\n");
      out.write("\t\t\t\t\t\t\t<span><span class=\"fa fa-clock-o\"></span> 5:30 PM</span> <br>\r\n");
      out.write("\t\t\t\t\t\t\t<span><span class=\"fa fa-calendar\"></span> April 22, 2018</span>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary btn-sm\">Join from\r\n");
      out.write("\t\t\t\t\t\t\t\t150.000vnd</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- .section -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/animate.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/owl.carousel.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/fonts/ionicons/css/ionicons.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/fonts/fontawesome/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Theme Style -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" <footer class=\"site-footer\" role=\"contentinfo\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row mb-5\">\r\n");
      out.write("          <div class=\"col-md-4 mb-5\">\r\n");
      out.write("            <h3>About Us</h3>\r\n");
      out.write("             <img  class=\"mb-5\" src=\"");
      out.print(request.getContextPath());
      out.write("/img/logo.png\" style=\"margin-top: 20px; position: absolute; width: 40% ; margin-bottom: 50px;\">\r\n");
      out.write("          \r\n");
      out.write("            <p class=\"mb-5\">Someone who is lively and active\r\n");
      out.write("            </p>\r\n");
      out.write("          \r\n");
      out.write("            <br>\r\n");
      out.write("             <br>\r\n");
      out.write("            <ul class=\"list-unstyled footer-link d-flex footer-social\">\r\n");
      out.write("              <li><a href=\"#\" class=\"p-2\"><span class=\"fa fa-twitter\"></span></a></li>\r\n");
      out.write("              <li><a href=\"#\" class=\"p-2\"><span class=\"fa fa-facebook\"></span></a></li>\r\n");
      out.write("              <li><a href=\"#\" class=\"p-2\"><span class=\"fa fa-linkedin\"></span></a></li>\r\n");
      out.write("              <li><a href=\"#\" class=\"p-2\"><span class=\"fa fa-instagram\"></span></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-5 mb-5\">\r\n");
      out.write("            <h3>Contact Info</h3>\r\n");
      out.write("            <ul class=\"list-unstyled footer-link\">\r\n");
      out.write("              <li class=\"d-block\">\r\n");
      out.write("                <span class=\"d-block\">Address:</span>\r\n");
      out.write("                <span class=\"text-white\">Khu pho 6, Linh Trung, Thu Duc, Tp HCM</span></li>\r\n");
      out.write("              <li class=\"d-block\"><span class=\"d-block\">Telephone:</span><span class=\"text-white\">0395362466</span></li>\r\n");
      out.write("              <li class=\"d-block\"><span class=\"d-block\">Email:</span><span class=\"text-white\">ngothimylinh@gmail.com</span></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-3 mb-5\">\r\n");
      out.write("            <h3>Quick Links</h3>\r\n");
      out.write("            <ul class=\"list-unstyled footer-link\">\r\n");
      out.write("              <li><a href=\"#\">About</a></li>\r\n");
      out.write("              <li><a href=\"#\">Terms of Use</a></li>\r\n");
      out.write("              <li><a href=\"#\">Disclaimers</a></li>\r\n");
      out.write("              <li><a href=\"#\">Contact</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-3\">\r\n");
      out.write("          \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-12 text-md-center text-left\">\r\n");
      out.write("            <p>&copy; <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --> <br> Demo Images Unsplash</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- END footer -->\r\n");
      out.write("\r\n");
      out.write("    <!-- loader -->\r\n");
      out.write("    <div id=\"loader\" class=\"show fullscreen\"><svg class=\"circular\" width=\"48px\" height=\"48px\"><circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke=\"#eeeeee\"/><circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#f4b214\"/></svg></div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/magnific-popup-options.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
